#### TP1: 

        * Dataset: Achat

* Nettoyage de données
*  Normalisations des données en utilisant différentes méthode
* Encodage de données
* La réduction des données en utilisant le thechnique PCA

##### Import des bibliothèques

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import impute
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn import compose 
from sklearn.decomposition import PCA 

#####  1- lécture et affichage des données

In [4]:
df = pd.read_csv('datasets/achat.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

##### 2- Affichage de nombre des instances de la base de données 

In [5]:
df.shape

(10, 4)

##### 3- Affichage des premières lignes de la base de données

In [6]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

##### 4- Séparation des variables indépendantes (X) et dépendante (Y)

In [7]:
X = df.iloc[:, :-1].values

In [8]:
Y = df.iloc[:, -1].values

##### 5- Nettoyage des données

In [9]:
# création d'une instance de SimpleImputer
imputer = impute.SimpleImputer(missing_values = np.nan, strategy ='mean') 

In [10]:
# Ajustement du SimpleImputer aux données X[:, 1:3] avec fit transform
X[:, 1:3] = imputer.fit_transform(X[:, 1:3]) 

##### 6- Affichage des premiers lignes de X après la phase de nettoyage

In [11]:
print (X[:5]) 

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]]


##### 7- Normalisation des données

In [30]:
# Création d'une instance de transformateur de normalisation
scaler = preprocessing.StandardScaler()

In [ ]:
# Normalisation des données
X[:, 1:3] = scaler.fit_transform(X) 

##### 8- Affichage des premières lignes après la normalisation

In [22]:
print (X[:5]) 

[['France' 0.758874361590019 0.7494732544921677]
 ['Spain' -1.7115038793306814 -1.4381784072687531]
 ['Germany' -1.2755547779917342 -0.8912654918285229]
 ['Spain' -0.1130238410878753 -0.253200423814921]
 ['Germany' 0.17760889313808945 6.632191985654332e-16]]


##### 9- Encodage de la colonne catégorielle 'country'

In [15]:
# Encodage des variables indépendantes 
ct = compose.ColumnTransformer(transformers = [('encoder', preprocessing.OneHotEncoder(), [0])], remainder = 'passthrough')
X_encoder= np.array(ct.fit_transform(X)) 


##### 10- Affichage des premières lignes après l'Encodage

In [16]:
print (X_encoder[:5])

[[1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]]


##### 11- Réduction des attributs Age et Salary en seul attribut

In [45]:
# Création du modèle 
model = PCA (n_components = 1) 
X_pca = model.fit_transform(X[:, 1:3]) 

In [46]:
# Exécution du modèle PCA 
print (X_pca.shape, X.shape) 

(10, 1) (10, 3)


##### 12- Affichage des premières lignes après la réduction

In [50]:
print (X_pca[:5]) 

[[ 1.06656283]
 [-2.2271617 ]
 [-1.53217331]
 [-0.25895966]
 [ 0.12558845]]
